"""NosAi perception foundation: observe and classify, never send input."""
from nosai.perception.contracts import (
    FrameObservation,
    OcrObservation,
    PixelBridgeObservation,
    TemplateObservation,
    YoloDetection,
    YoloObservation,
    classify_frame,
    classify_ocr,
    classify_template,
    classify_yolo,
    derived_value,
    unknown_value,
)
from nosai.perception.pixel_bridge import (
    PIXEL_BRIDGE_ANCHOR_RGB,
    PIXEL_BRIDGE_BLOCK_COUNT,
    PixelBridgeBlock,
    decode_pixel_bridge,
    encode_pixel_bridge_packet,
)
from nosai.perception.vision import (
    OcrSource,
    ScreenshotSource,
    TemplateSource,
    UnavailableOcrSource,
    UnavailableScreenshotSource,
    UnavailableTemplateSource,
    UnavailableYoloSource,
    YoloSource,
)

__all__ = [
    "FrameObservation",
    "OcrObservation",
    "OcrSource",
    "PIXEL_BRIDGE_ANCHOR_RGB",
    "PIXEL_BRIDGE_BLOCK_COUNT",
    "PixelBridgeBlock",
    "PixelBridgeObservation",
    "ScreenshotSource",
    "TemplateObservation",
    "TemplateSource",
    "UnavailableOcrSource",
    "UnavailableScreenshotSource",
    "UnavailableTemplateSource",
    "UnavailableYoloSource",
    "YoloDetection",
    "YoloObservation",
    "YoloSource",
    "classify_frame",
    "classify_ocr",
    "classify_template",
    "classify_yolo",
    "decode_pixel_bridge",
    "derived_value",
    "encode_pixel_bridge_packet",
    "unknown_value",
]
